---
AWSTemplateFormatVersion: '2010-09-09'
Description: Workstation
Mappings:
  AWSRegion2AMI:
    eu-central-1:
      AMI: ami-0bdf93799014acdc4
Parameters:
  InstanceType:
    AllowedValues:
    - t2.nano
    - t2.micro
    - t2.medium
    - c5.xlarge
    - m5.large
    ConstraintDescription: must be a valid EC2 instance type.
    Default: t2.micro
    Description: Instance type for EC2 instance.
    Type: String
  KeyName:
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
    Default: box
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
  HostedZone:
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: can contain only ASCII characters.
    Default: example.com.
    Description: zone name
    MaxLength: '255'
    MinLength: '1'
    Type: String
Resources:
  EIP:
    Type: "AWS::EC2::EIP"
    Properties:
      Domain: vpc
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [ AWSRegion2AMI, !Ref "AWS::Region", AMI ]
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups: [!Ref SecurityGroup]
      IamInstanceProfile:
        !Ref RootInstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20  # for them dockerz
      Tags:
      - Key: Name
        Value: !Join [ "-", [EC2, !Ref "AWS::StackName"] ]
      UserData:
        Fn::Base64: !Sub |
          #cloud-config
          write_files:
            - content: |
                PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
                LC_ALL=en_US.UTF-8
                LANG=en_US.UTF-8
              path: /etc/environment

          package_update: true

          package_upgrade: true

          packages:
            - awscli
            - docker.io
            - git
            - htop
            - mc
            - mosh

          runcmd:
            - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
            - LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 mosh-server
  EIPAssociation:
    Type: "AWS::EC2::EIPAssociation"
    Properties:
      AllocationId: !GetAtt EIP.AllocationId
      InstanceId: !Ref Instance
  SecurityGroup:
    Properties:
      GroupDescription: 'Enable access to the instance. '
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '60000'
        IpProtocol: udp
        ToPort: '61000'
      Tags:
      - Key: Name
        Value: !Join [ "-", [SG, !Ref "AWS::StackName"] ]
    Type: AWS::EC2::SecurityGroup
  RootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: "ecr:*"
          Resource: "*"
      Roles:
      - !Ref RootRole
  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: "/"
      Roles:
      - !Ref RootRole
  MyDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZone
      Comment: CNAME for the server
      Name: !Join [ ".", [!Ref "AWS::StackName", !Ref HostedZone] ]
      Type: CNAME
      TTL: 300
      ResourceRecords: [ !GetAtt Instance.PublicDnsName ]
